//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbhproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public System.Guid VehicleID { get; set; }
        public string SSN { get; set; }
        public int VTypeCode { get; set; }
        public int TCCode { get; set; }
        public int VMakeCode { get; set; }
        public int BCCode { get; set; }
        public string Tag { get; set; }
        public string TagExpiration { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    }
}
