//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbhproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public System.Guid VTypeID { get; set; }
        public int VTypeCode { get; set; }
        public string VTypeName { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
