//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbhproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDriver
    {
        public System.Guid DriverID { get; set; }
        public string SSN { get; set; }
        public string OLN { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public int StateCode { get; set; }
        public string PostalCode { get; set; }
        public string Gender { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public int EyeColorCode { get; set; }
        public int HairColorCode { get; set; }
        public bool OrganDonor { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.Guid> StateID { get; set; }
        public Nullable<int> StatesStateCode { get; set; }
        public string StateAbbr { get; set; }
        public string StateName { get; set; }
        public Nullable<bool> StatesActive { get; set; }
        public Nullable<bool> StatesDeleted { get; set; }
        public Nullable<System.DateTime> StatesCreateDate { get; set; }
        public Nullable<System.Guid> EyeColorID { get; set; }
        public Nullable<int> EyeCode { get; set; }
        public string EyeColorAbbr { get; set; }
        public string EyeColorName { get; set; }
        public Nullable<bool> EyeColorActive { get; set; }
        public Nullable<System.DateTime> EyeColorCreateDate { get; set; }
        public Nullable<bool> EyeColorDeleted { get; set; }
        public Nullable<System.Guid> HairColorID { get; set; }
        public Nullable<int> HairCode { get; set; }
        public string HairColorAbbr { get; set; }
        public string HairColorName { get; set; }
        public Nullable<bool> HairActive { get; set; }
        public Nullable<bool> HairDeleted { get; set; }
        public Nullable<System.DateTime> HairCreateDate { get; set; }
        public System.Guid LicenseID { get; set; }
        public string LicenseCode { get; set; }
        public int LicenseState { get; set; }
        public int LicenseCounty { get; set; }
        public string LicenseStatus { get; set; }
        public string LicenseClass { get; set; }
        public string LicenseRestrictions { get; set; }
        public string LicenseEndorsements { get; set; }
        public string LicenseIssue { get; set; }
        public string LicenseExpiration { get; set; }
        public bool LicenseActive { get; set; }
        public bool LicenseDeleted { get; set; }
        public System.DateTime LicenseCreateDate { get; set; }
        public System.DateTime LicenseLastUpdate { get; set; }
    }
}
