//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbhproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVehicle
    {
        public System.Guid VehicleID { get; set; }
        public string SSN { get; set; }
        public int VTypeCode { get; set; }
        public int TCCode { get; set; }
        public int VMakeCode { get; set; }
        public int BCCode { get; set; }
        public string Tag { get; set; }
        public string TagExpiration { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> VTypeID { get; set; }
        public Nullable<int> VTypeVTypeCode { get; set; }
        public string VTypeName { get; set; }
        public Nullable<bool> VTypeActive { get; set; }
        public Nullable<bool> VTypeDeleted { get; set; }
        public Nullable<System.DateTime> VTypeLastUpdate { get; set; }
        public Nullable<System.DateTime> VTypeCreateDate { get; set; }
        public Nullable<System.Guid> VMakeID { get; set; }
        public Nullable<int> VMakeVMakeCode { get; set; }
        public string VMakeName { get; set; }
        public Nullable<bool> VMakeActive { get; set; }
        public Nullable<bool> VMakeDeleted { get; set; }
        public Nullable<System.DateTime> VMakeCreateDate { get; set; }
        public Nullable<System.Guid> TopColorID { get; set; }
        public Nullable<int> TopColorCode { get; set; }
        public string TopColorAbbr { get; set; }
        public string TopColorName { get; set; }
        public Nullable<bool> TopColorActive { get; set; }
        public Nullable<bool> TopColorDeleted { get; set; }
        public Nullable<System.DateTime> TopColorCreateDate { get; set; }
        public Nullable<System.Guid> BottomColorID { get; set; }
        public Nullable<int> BottomColorCode { get; set; }
        public string BottomColorAbbr { get; set; }
        public string BottomColorName { get; set; }
        public Nullable<bool> BottomColorActive { get; set; }
        public Nullable<bool> BottomColorDeleted { get; set; }
        public Nullable<System.DateTime> BottomColorCreateDate { get; set; }
    }
}
